<<<<<<< HEAD
# Generated by Django 2.1.dev20171005184450 on 2018-01-10 07:07

from django.db import migrations, models
=======
# Generated by Django 2.0.1 on 2018-01-10 19:20

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
>>>>>>> afd09bc40776383374773cff59ac86a57bc060ea


class Migration(migrations.Migration):

    initial = True

    dependencies = [
<<<<<<< HEAD
=======
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
>>>>>>> afd09bc40776383374773cff59ac86a57bc060ea
    ]

    operations = [
        migrations.CreateModel(
<<<<<<< HEAD
            name='Villains',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('writter_id', models.CharField(max_length=24)),
=======
            name='Villain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
>>>>>>> afd09bc40776383374773cff59ac86a57bc060ea
                ('villain_name', models.CharField(max_length=24)),
                ('univ', models.CharField(max_length=24)),
                ('major', models.CharField(max_length=24)),
                ('class_name', models.CharField(max_length=24)),
<<<<<<< HEAD
                ('bomb', models.IntegerField(default=1)),
                ('content', models.CharField(max_length=3000)),
                ('update_date', models.DateTimeField()),
=======
                ('bomb', models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(1)])),
                ('content', models.CharField(max_length=3000)),
                ('update_date', models.DateTimeField(auto_now=True)),
                ('writter_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
>>>>>>> afd09bc40776383374773cff59ac86a57bc060ea
            ],
        ),
    ]
