# Generated by Django 2.0.1 on 2018-01-10 19:20

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Villain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('villain_name', models.CharField(max_length=24)),
                ('univ', models.CharField(max_length=24)),
                ('major', models.CharField(max_length=24)),
                ('class_name', models.CharField(max_length=24)),
                ('bomb', models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(1)])),
                ('content', models.CharField(max_length=3000)),
                ('update_date', models.DateTimeField(auto_now=True)),
                ('writter_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
