# Generated by Django 2.1.dev20171005184450 on 2018-01-10 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Villains',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('writter_id', models.CharField(max_length=24)),
                ('villain_name', models.CharField(max_length=24)),
                ('univ', models.CharField(max_length=24)),
                ('major', models.CharField(max_length=24)),
                ('class_name', models.CharField(max_length=24)),
                ('bomb', models.IntegerField(default=1)),
                ('content', models.CharField(max_length=3000)),
                ('update_date', models.DateTimeField()),
            ],
        ),
    ]
