# Generated by Django 2.0.1 on 2018-01-10 19:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('villains', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='villain',
            name='writter_id',
        ),
    ]
