# Generated by Django 2.1.dev20171005184450 on 2018-01-10 07:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('villains', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Villain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('writter_id', models.CharField(max_length=24)),
                ('villain_name', models.CharField(max_length=24)),
                ('univ', models.CharField(max_length=24)),
                ('major', models.CharField(max_length=24)),
                ('class_name', models.CharField(max_length=24)),
                ('bomb', models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(1)])),
                ('content', models.CharField(max_length=3000)),
                ('update_date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Villains',
        ),
    ]
