# Generated by Django 2.1.dev20171005184450 on 2018-01-10 08:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('villains', '0002_auto_20180110_1636'),
    ]

    operations = [
        migrations.AlterField(
            model_name='villain',
            name='writter_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
