# Generated by Django 2.1.dev20171005184450 on 2018-01-10 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('villains', '0003_auto_20180110_1701'),
    ]

    operations = [
        migrations.AlterField(
            model_name='villain',
            name='writter_id',
            field=models.CharField(max_length=24),
        ),
    ]
