# Generated by Django 2.1.dev20171005184450 on 2018-01-14 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('villains', '0006_villain_agree'),
    ]

    operations = [
        migrations.AlterField(
            model_name='villain',
            name='writter_id',
            field=models.CharField(max_length=24),
        ),
    ]
