# Generated by Django 2.1.dev20171005184450 on 2018-01-24 06:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('villains', '0007_auto_20180115_0316'),
    ]

    operations = [
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('liker_id', models.CharField(max_length=24)),
                ('villain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='villains.Villain')),
            ],
        ),
    ]
