# Generated by Django 2.1.dev20171005184450 on 2018-01-24 07:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('villains', '0008_like'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agreer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agreer_id', models.CharField(max_length=24)),
                ('villain_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='villains.Villain')),
            ],
        ),
        migrations.RemoveField(
            model_name='like',
            name='villain',
        ),
        migrations.DeleteModel(
            name='Like',
        ),
    ]
