# Generated by Django 2.1.dev20171005184450 on 2018-01-24 19:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('villains', '0011_auto_20180125_0348'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='villain',
            name='agree_count',
        ),
    ]
