# Generated by Django 2.0.2 on 2018-05-18 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('villains', '0012_remove_villain_agree_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='villain',
            name='is_update',
            field=models.IntegerField(default=-1),
        ),
    ]
